<?php
alert("hello");
/*
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
*/
/*
require_once('phpmailer/class.phpmailer.php');
require_once('phpmailer/class.smtp.php');


$mail = new PHPMailer();
// $mail->SMTPDebug = 3;                               // Enable verbose debug output
$mail->isSMTP();                                      // Set mailer to use SMTP
$mail->Host = 'smtp.gmail.com';                  // Specify main and backup SMTP servers
$mail->SMTPAuth = true;                               // Enable SMTP authentication
$mail->Username = 'admissions@charusat.ac.in';    // SMTP username
$mail->Password = 'ecchanga';                         // SMTP password
$mail->SMTPSecure = 'tls';                            // Enable TLS encryption, `ssl` also accepted
$mail->Port = 587;                                    // TCP port to connect to

$status = "false";

if( $_POST['name'] != '' AND $_POST['email'] != '' AND $_POST['subject'] != '' AND $_POST['comments'] != '') {

        $name = $_POST['name'];
        $email = $_POST['email'];
        $subject = $_POST['subject'];
        $message = $_POST['comments'];
        $subject = isset($subject) ? $subject : 'Admission Enquiry';
        $name = isset($_POST['fname']) ? $_POST['fname'] : '';
        $botcheck = $_POST['form_botcheck'];
  		$msg = isset($_POST['msg']) ? $_POST['msg'] : '--';
  
		$toemail = 'jalpeshvasa.it@charusat.ac.in'; // Your Email Address // where to send query
        $toname = 'CHARUSAT';                // Receiver Name
		
  		$referrer = '';
        
       if( $botcheck == '' ) {

            $mail->AddReplyTo( $email , $name ); // reply to query
            $mail->SetFrom( $email , $name );   // who send query
        	//$mail->FromName = "Full Name";   
         	
         
         	$mail->From = $toemail;	
			$mail->FromName = $toname;
         
            $mail->AddAddress( $toemail , $toname ); // where to send query
            $mail->Subject = $subject;

            $name = isset($name) ? "Name: $name<br>" : '';
            $email = isset($email) ? "Email: $email<br>" : '';
            $phone = isset($phone) ? "Phone: $phone<br>" : '';
         	$branch = isset($branch) ? "Branch: $branch<br>" : '';
         	$admission_category = isset($admission_category) ? "Admission Category: $admission_category<br><br>" : '';
         
         	$msg = isset($msg) ? "<strong>Query</strong>: $msg<br>" : '';
         
         
            // $referrer = $_SERVER['HTTP_REFERER'] ? '<br><br><br>This is autogenerated emailThis Form was submitted from: ' . $_SERVER['HTTP_REFERER'] : '';

         	$body = "$name $email $phone $branch $admission_category $msg ";

            $mail->MsgHTML( $body );
            $sendEmail = $mail->Send();

            if( $sendEmail == true ):
                $message = 'We have successfully received your Message and will get Back to you as soon as possible.';
                $status = "true";
            else:
                
         		echo $body."<br>";
         		$message = 'Email could not be sent due to some Unexpected Error. Please Try Again later.<br /><br /><strong>Reason:</strong><br />' . $mail->ErrorInfo . '';
                $status = "false";
            endif;
         } else {
          $message = 'Bot Detected.!!';
           $status = "false";
        }
    } else {
        $message = 'Please Fill up all the Fields and Try Again.';
        $status = "false";
    }

    $status_array = array( 'message' => $message, 'status' => $status);
    echo json_encode($status_array);  
// echo $mail->ErrorInfo;

*/
?>